### ISSUE TITLE
[FEAT] 사진 선물 보내기

### ISSUE THREAD

**Issue by Rookie0031** [ECube-Reboot/LiveOn-Reborn-iOS#11]
## 💡 Issue
유저가 사진을 보내는데 필요한 기능과 View 구현 및 연결을 담당합니다.

## 📝  todo

- [ ] Task1: 맨 처음 선물할 때, 선물할 사진을 선택시, 기기에 접근 권한 요청 모달로 띄우기
- [ ] Task2: 사진 선택시, 카메라 바로 열기 기능 추가
- [ ] Task3: 사진 보관함에서 사진 선물하기 뷰로 갈 수 있는 Navi button 추가
- [ ] Task4: 개선된 폴더링 구조에 코드 옮기기
