### ISSUE TITLE
[FEAT] 꽃 선물 보내기

### ISSUE THREAD

**Issue by teethemoji** [ECube-Reboot/LiveOn-Reborn-iOS#14]
## 💡 Issue
유저가 꽃 선물을 제작하고 전송하는데 필요한 모델, 기능과 View를 구현합니다.

## 📝  todo
- [x] Task 1 : Flower Model 제작
- [ ] Task 2 : 오늘의 꽃을 확인
- [ ] Task 3 : 짧은 쪽지 작성 창 구현
- [ ] Task 4 : 전송하기 버튼 구현
