### ISSUE TITLE
[FEAT] 음성메시지 녹음 UI 및 기능 부분 구현

### ISSUE THREAD

**Issue by seongmin221** [ECube-Reboot/LiveOn-Reborn-iOS#18]
## 💡 Issue
음성메세지 녹음 UI와 기본 기능 구현
일단은 progress bar는 후순위로 두고 진행하겠습니다!

## 📝  todo
- [ ] 음성메세지 녹음 UI 구현
- [ ] record 버튼을 누르면 녹음이 시작되고, stop 버튼으로 바뀐다
- [ ] stop 버튼을 누르면 녹음이 완료되고, play, pause, record again 버튼으로 바뀐다
- [ ] 음성메세지 녹음 기능 구현
