### ISSUE TITLE
[FEAT] 달력 날짜 이동 버튼 및 Upcoming Events UI 수정

### ISSUE THREAD

**Issue by italsehf** [ECube-Reboot/LiveOn-Reborn-iOS#23]
## 💡 Issue
달력 메인화면에서의 UI를 개선합니다.

## 📝  todo
- [x] 달력 이동 버튼인 화살표를 해당 월의 이전달/다음달로 버튼 UI 수정
- [x] 달력 이동 버튼 이외에 스와이프로 해당 월의 이전달/다음달 이동 기능 추가
- [x] 기념일을 추가하고 작성하는 화면 UI 수정
- [x] Upcoming Events UI 수정
- [x] Upcoming Events - Text 구조 및 레이아웃 수정
- [x] Upcoming Events - 기념일이 없는 경우 default 문구 설정하기
- [x] 기념일이 있을 경우 달력에 하이라이트로 표시
