### ISSUE TITLE
[FEAT] 메인 선물함 View UI 구현

### ISSUE THREAD

**Issue by teethemoji** [ECube-Reboot/LiveOn-Reborn-iOS#29]
# 💡 Issue
달력, 쪽지, 사진, 음성 메시지, 선물함으로 갈 수 있는 메인 선물함 뷰를 구현합니다.

# 📝  todo
### 상단 헤더
- [x] 커플 라벨 스티커 
- [x] 선물 제작 뷰 이동 버튼

## 기능 구현
- [x] 네비게이션 링크로 이동 기능
