### ISSUE TITLE
[FEAT] 로그인 status에 따른 분기 처리, 회원정보 api 연동

### ISSUE THREAD

**Issue by jinccc97** [ECube-Reboot/LiveOn-Reborn-iOS#46]
## 💡 Issue
- 로그인 상황에 따라 첫 화면 분기처리합니다.
- 회원정보 api를 연결합니다.
- 토큰 만료 처리 로직짭이다.

## 📝  todo
- [ ] 로그인 상태나누고 첫 화면 설정
- [ ] 회원정보 get,post api 연동
- [ ] 토큰 만료시 새로 토큰 발급
- [ ]
