### ISSUE TITLE
[FEAT] urlsession api 연동 기본 설정

### ISSUE THREAD

**Issue by jola7373** [ECube-Reboot/LiveOn-Reborn-iOS#6]
## 💡 Issue

공통되는 api 연동에 필요한 설정하기

## 📝  todo
- [ ] 공통 api endpoint 설정
- [ ] header에 bearer token 넣는 설정
- [ ] 예시 작성 - test api
